{
 "title": "Faust Microservices Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "data_collection: Number of Values per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(sensor_values_received_total{instance=\"collection:7002\"}[60s])",
     "legendFormat": "sensor values received"
    },
    {
     "expr": "increase(sensor_values_collected_total{instance=\"collection:7002\"}[60s])",
     "legendFormat": "sensor values collected"
    },
    {
     "expr": "increase(sensor_values_sent_total{instance=\"collection:7002\"}[60s])",
     "legendFormat": "sensor values sent"
    }
   ]
  },
  {
   "title": "data_processing: Number of Values per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(sensor_values_received_total{instance=\"processing:7003\"}[60s])",
     "legendFormat": "sensor values received"
    },
    {
     "expr": "increase(sensor_values_processed_total{instance=\"processing:7003\"}[60s])",
     "legendFormat": "sensor values processed"
    },
    {
     "expr": "increase(sensor_values_sent_total{instance=\"processing:7003\"}[60s])",
     "legendFormat": "sensor values sent"
    }
   ]
  },
  {
   "title": "data_aggregation: Number of Values per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(sensor_values_received_total{instance=\"aggregation:7004\"}[60s])",
     "legendFormat": "sensor values received"
    },
    {
     "expr": "increase(sensor_values_aggregated_total{instance=\"aggregation:7004\"}[60s])",
     "legendFormat": "sensor values aggregated"
    },
    {
     "expr": "increase(sensor_values_sent_total{instance=\"aggregation:7004\"}[60s])",
     "legendFormat": "sensor values sent"
    }
   ]
  },
  {
   "title": "db_loader: Number of Values per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(sensor_values_loaded_total{instance=\"load:7005\"}[60s])",
     "legendFormat": "sensor values loaded into db"
    },
    {
     "expr": "increase(aggregated_values_loaded_total{instance=\"load:7005\"}[60s])",
     "legendFormat": "aggregated values loaded into db"
    }
   ]
  },
  {
   "title": "api_gateway: Number of REST API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sensor_values_requests_total{instance=\"api-gateway:7006\"}",
     "legendFormat": "sensor value requests"
    },
    {
     "expr": "aggregated_values_requests_total{instance=\"api-gateway:7006\"}",
     "legendFormat": "aggregated value requests"
    },
    {
     "expr": "latest_value_requests_total{instance=\"api-gateway:7006\"}",
     "legendFormat": "latest value requests"
    }
   ]
  },
  {
   "title": "api_gateway: Age of Requested Latest Values",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "latest_value_requests_age_seconds_bucket{instance=\"api-gateway:7006\"}",
     "legendFormat": "cumulative bucket for age <= {{le}} seconds"
    }
   ]
  }
 ]
}