global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'collection'
    metrics_path: /metrics
    static_configs:
      - targets: ['collection:7002']
  - job_name: 'processing'
    metrics_path: /metrics
    static_configs:
      - targets: ['processing:7003']